name: Bug Report (in English)
description: >-
  Recognition errors, operation abnormalities,
  connection errors, etc.
labels: ['s:error']
assignees: ['deng-rui']
body:
  - type: checkboxes
    id: checks
    attributes:
      label: Before raising the issue...
      options:
      - label: >-
          I understand that Issues are for feedback and problem solving,
          not trolling the comments section, and will provide as
          much information as possible to help solve the problem.
        required: true
      - label: >-
          I filled in a short, clear title
          so that developers could quickly identify the general problem
          when going through the issue list.
          Instead of "Some suggestions", "Stuck", etc.
        required: true
      - label: >-
          I have checked the latest beta update and there is no mention
          of the bug being fixed.
        required: true
  - type: textarea
    id: describe
    attributes:
      label: Description
      description: Describe your problem in as much detail as possible.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Log files
      description: >-
        **Upload `Log.txt` in the `data/log` folder, stating the approximate point in time when the problem occurred**.
        **Please drag and drop the complete file directly into the folder, rather than cutting or copying pieces yourself; if the file is too large, compress it and upload it again**.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: >-
        If available, add screenshots to help explain your problem,
        Including but not limited to Server console screenshots,
        screenshots of game screens.
    validations:
      required: false
  - type: textarea
    id: others
    attributes:
      label: Anthing else?
      description: >-
        Java publisher version, operating system, related configuration, links,
        reference material, etc.

        Anything that will give us more insight into the problem
        you are having.
    validations:
      required: false