name: Java CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_jar:
    continue-on-error: true
    strategy:
      matrix:
        jdk: [ 21 ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jdk }}

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew jar

      - name: Upload Server-All.jar 2 Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Server-All-JDK${{ matrix.jdk }}
          path: ./Server-All/build/libs/*.jar
